
-- Insert data into Role table
INSERT INTO role (id, type, create_at, update_at) VALUES
    (1, 'STUDENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'INSTRUCTOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);