-- Insert data into Campus table
INSERT INTO campus (id, name, location, create_at, update_at) VALUES
    (1, 'FU_HL', 'Hà Nội - Hòa Lạc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'FU_HCM', 'Hồ Chí Minh',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'FU_DN', 'ĐÀ NẴNG',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'FU_CT', 'CẦN THƠ',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'FU_QN', 'QUY NHƠN',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);