
-- Insert data into Role table
INSERT INTO role (id, type, create_at, update_at) VALUES
    (1, 'ROLE_STUDENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'ROLE_INSTRUCTOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'ROLE_MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'ROLE_ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);