
-- Insert data into Role table
INSERT INTO role (id, type, name, create_at, update_at) VALUES
    (1, 'ROLE_STUDENT', 'STUDENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'ROLE_INSTRUCTOR', 'INSTRUCTOR',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'ROLE_MANAGER', 'MANAGER',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'ROLE_ADMIN', 'ADMIN',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);